config/routes.rb
Rails.application.routes.draw do
  # mount Blazer::Engine, at: "blazer"
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "/teams/:id/staff", to: "teams#staff", as: "staff"
  get "/teams/:id/management", to: "management#index", as: "management"
  get "/teams/:id/chat", to: "teams#chat", as: "chat"
  get '/search', to: 'search#search'
  
  resources :teams, only: :show do
    resources :management, only: [:index, :show]

    resources :chatrooms do
      resources :messages, only: :create
    end

    resources :events, except: :destroy
    resources :players, except: :destroy
    resources :employees, except: :destroy
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :team
  has_many :event_employees, dependent: :destroy
  has_many :events, through: :event_employees

  validates :first_name, :last_name, :role, :birthdate, presence: true

  def employee_full_name
    first_name + " " + last_name
  end

  include PgSearch::Model
  multisearchable against: %i[first_name last_name role]
  PgSearch.multisearch_options = {
    using: { tsearch: { prefix: true } }
  }
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employees, only: %i[show edit update]
  before_action :set_team

  def index
    @employees = Employee.all
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.team = @team
    @employee.save
    if @employee.save
      redirect_to team_employees_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @employee.update(employee_params)
    @employee.save

    redirect_to team_employee_path(@employee)
  end

  private

  def set_employees
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :role, :birthdate)
  end

  def set_team
    @team = current_user.team
    # @team = Team.find(params[:team_id])
  end
end

app/views/employees/_employee_card.html.erb
<div class="col-12 col-md-4 p-0">
  <%= link_to team_employee_path(@team, employee) do %>
    <div class="employee-card">
        <div class="p-0">
          <h5><%= employee.first_name %> <%= employee.last_name %></h5>
          <h6><%= employee.role %></h6>
      </div>
    </div>
  <% end %>
</div>

app/views/employees/_form.html.erb
<%= simple_form_for [team, employee] do |f| %>
    <%= f.input :first_name,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "First name" }%>
    <%= f.input :last_name,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Last name" }%>
    <%= f.input :role,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Role" }%>
    <%= f.input :birthdate,
                input_html: { autocomplete: "email", style: "background: white;" },
                label_html: { class: "h6", style: "color: #2D7D9F;"}%>
    <%= f.submit class: 'custom-button btn btn-primary'%>
<% end %>

app/views/employees/edit.html.erb
<div class="container h-100 d-flex align-items-center justify-content-center">
  <div class="login form p-5 w-50 shadow mt-5 bg-white rounded-4">

    <%= link_to team_players_path do %>
      <i class="fas fa-2x fa-chevron-circle-left" style="color: #dddddd;"></i>
    <% end %>

    <h2 class="text-center text-primary">Edit Employee</h2>
    <div class="mt-3">
      <%= render "form", employee: @employee, team: @team %>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="container">
  <h2>All employees</h2>
  <%= link_to "Back to team dashboard", team_path(@team) %>
  <%= link_to "Add new employee", new_team_employee_path(@team) %>
  <% if @employees.any? %>
    <div class="d-flex row">
      <% @employees.each do |employee| %>
        <%= render "employee_card", employee: employee %>
      <% end %>
    </div>
  <% else %>
    <p>No employees yet</p>
  <% end %>
</div>

app/views/employees/new.html.erb
<div class="container h-100 d-flex align-items-center justify-content-center">
  <div class="login form p-5 w-50 shadow mt-5 bg-white rounded-4">

    <%= link_to team_employees_path(@team) do %>
      <i class="fas fa-2x fa-chevron-circle-left" style="color: #dddddd;"></i>
    <% end %>
    <h2 class="text-center text-primary">Add Employee</h2>

    <div class="mt-3">
      <%= render "form", employee: @employee, team: @team %>
    </div>

 </div>
</div>

app/views/employees/show.html.erb
<div class="container profile">
  <div class="d-flex">
    <h1 class="fw-light mx-3 mb-0"><%= @employee.first_name %> <%= @employee.last_name %></h1>
    </div>
  <h3 class="my-3"><%= @employee.role %></h3>
  <h4><%= @employee.birthdate.strftime("%d %B %Y") %></h4>
  <p>Notes and calendar go here</p>
  <p><%= link_to "Edit employee info", edit_team_employee_path(@employee) %> </p>
  <img src="https://img.freepik.com/free-vector/schedule-calendar-flat-style_78370-1550.jpg">
</div>