config/routes.rb
Rails.application.routes.draw do
  # mount Blazer::Engine, at: "blazer"
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "/teams/:id/staff", to: "teams#staff", as: "staff"
  get "/teams/:id/management", to: "management#index", as: "management"
  get "/teams/:id/chat", to: "teams#chat", as: "chat"
  get '/search', to: 'search#search'
  
  resources :teams, only: :show do
    resources :management, only: [:index, :show]

    resources :chatrooms do
      resources :messages, only: :create
    end

    resources :events, except: :destroy
    resources :players, except: :destroy
    resources :employees, except: :destroy
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div id="navbar" class="d-flex justify-content-between navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top border-bottom-success">
  <div class="mx-2 flex-grow-1">
  <% if controller_name == 'teams' && action_name == 'show' %>
    <h1 class="ms-5 fw-light text-primary">Dashboard</h1>
  <% end %>
  <% if controller_name == 'events' && action_name == 'index' %>
    <h1 class="ms-5 fw-light text-primary">Calendar</h1>
  <% end %>
  <% if controller_name == 'events' && action_name == 'show' %>
    <h1 class="ms-5 fw-light text-primary">Event</h1>
  <% end %>
  <% if controller_name == 'teams' && action_name == 'staff' %>
    <h1 class="ms-5 fw-light text-primary">Team Overview</h1>
  <% end %>
  <% if controller_name == 'players' && action_name == 'index' %>
    <h1 class="ms-5 fw-light text-primary">All Players</h1>
  <% end %>
  <% if controller_name == 'players' && action_name == 'new' %>
    <h1 class="ms-5 fw-light text-primary">New Player</h1>
  <% end %>
  <% if controller_name == 'players' && action_name == 'show' %>
    <h1 class="ms-5 fw-light text-primary">Player Profile</h1>
  <% end %>
   <% if controller_name == 'management' && action_name == 'index' %>
    <h1 class="ms-5 fw-light text-primary">Management</h1>
  <% end %>
  <% if controller_name == 'teams' && action_name == 'chat' %>
    <h1 class="ms-5 fw-light text-primary">Chat</h1>
  <% end %>
  <% if controller_name == 'chatrooms' && action_name == 'index' %>
    <h1 class="ms-5 fw-light text-primary">Message Inbox</h1>
  <% end %>
  <% if controller_name == 'chatrooms' && action_name == 'show' %>
    <h1 class="ms-5 fw-light text-primary">#<%= @chatroom.name %></h1>
  <% end %>
  <% if controller_name == 'chatrooms' && action_name == 'new' %>
    <h1 class="ms-5 fw-light text-primary">New Chat</h1>
  <% end %>
  <% if controller_name == 'search' && action_name == 'search' %>
    <h1 class="ms-5 fw-light text-primary">Search Results</h1>
  <% end %>
    </div>

  <div class="d-flex">
    <%= form_with url: search_path, method: :get, class: "d-flex w-200", id:"search-bar" do %>
      <%= text_field_tag :search,
        params[:search],
        class: "form-control me-2 bg-white rounded-4",
        id: "search-bar-input",
        placeholder: ""
      %>
      <%#= submit_tag "Search", name: "", class: "btn btn-outline-primary rounded-4 d-none", id: "search-bar-submit" %>
    <%# <i class="sidebar-button fa-solid fa-magnifying-glass", style="color: #D9D9D9" id="search-button"></i> %>
    <%= button_tag type: "submit", class: "btn rounded-4", id: "search-bar-submit" do %>
      <i class="sidebar-button fa-solid fa-magnifying-glass", style="color: #D9D9D9" id="search-bar-submit"></i>
    <% end %>

    <% end %>
  </div>

  <nav class="mx-2 d-flex align-items-center navbar navbar-expand-lg navbar-light p-3 " style="background-color: white">
      <div class="me-3 d-flex flex-column align-items-end">
        <h5><%= current_user.first_name %> <%= current_user.last_name %></h5>
        <h6>Team Manager</h6>
      </div>
      <a class="nav-link mx-2" href="#">
        <%= image_tag "liverpool_logo.png", class: "logo", position: :sticky %>
      </a>
  </nav>

</div>

app/views/shared/_sidebar.html.erb
<div class="wrapper">
    <!-- Sidebar -->
    <nav id="sidebar" class="d-flex flex-column align-items-center justify-content-between pb-3">
        <div class="sidebar-header cool-side">
          <%= link_to root_path do %>
            <%= image_tag "logo2.png", class: "company-logo" %>
          <% end %>
        </div>
          <ul data-controller="click" class="h-50 d-flex flex-column justify-content-around align-items-center cool-side list-unstyled components">

            <li>
              <div class="d-flex justify-content-center align-items-center <%= controller_name == 'teams' && action_name == 'show' ? 'very-cool-side' : '' %>">
                <%= link_to team_path(@team) do %>
                  <i class="sidebar-button fa-solid fa-house" style="<%= controller_name == 'teams' && action_name == 'show' ? 'color: #2D7D9F' : 'color: #D9D9D9;' %>"></i>
                <% end %>
              </div>
            </li>

            <li>
              <div  class="d-flex justify-content-center align-items-center <%= controller_name == 'events' && action_name == 'index' ? 'very-cool-side' : '' %>">
                <%= link_to team_events_path(@team) do %>
                  <i class="sidebar-button fa-regular fa-calendar" style="<%= controller_name == 'events' && action_name == 'index' ? 'color: #2D7D9F' : 'color: #D9D9D9;' %>"></i>
                <% end %>
              </div>
            </li>


            <li>
              <div class="d-flex justify-content-center align-items-center <%= controller_name == 'teams' && action_name == 'staff' ? 'very-cool-side' : '' %>">
                <%= link_to staff_path(@team) do %>
                  <i class="sidebar-button fa-solid fa-people-group" style="<%= controller_name == 'teams' && action_name == 'staff' ? 'color: #2D7D9F' : 'color: #D9D9D9;' %>"></i>
                <% end %>
              </div>
            </li>

            <li>
              <div class="d-flex justify-content-center align-items-center <%= controller_name == 'management' && action_name == 'index' ? 'very-cool-side' : '' %>">
                <%= link_to management_path(@team) do %>
                  <i class="sidebar-button fa-solid fa-bars-progress" style="<%= controller_name == 'management' && action_name == 'index' ? 'color: #2D7D9F' : 'color: #D9D9D9;' %>"></i>
                <% end %>
              </div>
            </li>

            <li>
              <div class="d-flex justify-content-center align-items-center <%= controller_name == 'chatrooms' && (action_name == 'index' || 'show') ? 'very-cool-side' : '' %>">
                <%= link_to team_chatrooms_path(@team) do %>
                  <i class="sidebar-button fa-solid fa-comments" style="<%= controller_name == 'chatrooms' && (action_name == 'index' || 'show') ? 'color: #2D7D9F' : 'color: #D9D9D9;' %>"></i>
                <% end %>
              </div>
            </li>

          </ul>
        <div class="d-flex align-items-center justify-content-center cool-side">
          <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
            <i class="sidebar-button fa-solid fa-right-from-bracket fa-rotate-180" style="color: #8c9093;"></i>
          <% end %>
        </div>
    </nav>
  </div>