config/routes.rb
Rails.application.routes.draw do
  # mount Blazer::Engine, at: "blazer"
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "/teams/:id/staff", to: "teams#staff", as: "staff"
  get "/teams/:id/management", to: "management#index", as: "management"
  get "/teams/:id/chat", to: "teams#chat", as: "chat"
  get '/search', to: 'search#search'
  
  resources :teams, only: :show do
    resources :management, only: [:index, :show]

    resources :chatrooms do
      resources :messages, only: :create
    end

    resources :events, except: :destroy
    resources :players, except: :destroy
    resources :employees, except: :destroy
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :team
  has_many :event_players, dependent: :destroy
  has_many :event_employees, dependent: :destroy
  has_many :players, through: :event_players
  has_many :employees, through: :event_employees
  accepts_nested_attributes_for :event_players

  OPPONENTS = {
    "Arsenal" => "https://resources.premierleague.com/premierleague/badges/rb/t3.svg",
    "Aston Villa" => "https://resources.premierleague.com/premierleague/badges/rb/t7.svg",
    "Bournemouth" => "https://resources.premierleague.com/premierleague/badges/rb/t91.svg",
    "Brentford" => "https://resources.premierleague.com/premierleague/badges/rb/t94.svg",
    "Brighton & Hove Albion" => "https://resources.premierleague.com/premierleague/badges/rb/t36.svg",
    "Burnley" => "https://resources.premierleague.com/premierleague/badges/rb/t90.svg",
    "Chelsea" => "https://resources.premierleague.com/premierleague/badges/rb/t8.svg",
    "Crystal Palace" => "https://resources.premierleague.com/premierleague/badges/rb/t31.svg",
    "Everton" => "https://resources.premierleague.com/premierleague/badges/rb/t11.svg",
    "Fulham" => "https://resources.premierleague.com/premierleague/badges/rb/t54.svg",
    "Luton Town" => "https://resources.premierleague.com/premierleague/badges/rb/t102.svg",
    "Manchester City" => "https://resources.premierleague.com/premierleague/badges/rb/t43.svg",
    "Manchester United" => "https://resources.premierleague.com/premierleague/badges/rb/t1.png",
    "Newcastle United" => "https://resources.premierleague.com/premierleague/badges/rb/t4.png",
    "Nottingham Forest" => "https://resources.premierleague.com/premierleague/badges/rb/t17.svg",
    "Sheffield United" => "https://resources.premierleague.com/premierleague/badges/rb/t49.svg",
    "Tottenham Hotspur" => "https://resources.premierleague.com/premierleague/badges/rb/t6.svg",
    "West Ham United" => "https://resources.premierleague.com/premierleague/badges/rb/t21.svg",
    "Wolverhampton Wanderers" => "https://resources.premierleague.com/premierleague/badges/rb/t39.svg"
  }

  EVENT_TYPE = %w[Match Meeting Gym Training Physio Other]

  validates :end_date, comparison: { greater_than: :start_date }, presence: true
  validates :location, :title, :description, :start_date, presence: true
  # validates :opposition, inclusion: { in: OPPONENTS.keys }
  validates :event_type, inclusion: { in: EVENT_TYPE }

  validate :opposition_presence_for_match_event

  include PgSearch::Model
  multisearchable against: %i[opposition event_type title]

  def opposition_presence_for_match_event
    if event_type == "Match" && !opposition.present?
      errors.add(:opposition, "is required for match events")
    end
  end

  def start_time
    self.start_date
  end

  def end_time
    self.end_date
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  helper_method :health_status

  def index
    @team = current_user.team
    @events = Event.where(start_date: Time.now.beginning_of_month.beginning_of_week..)
    # start_date = params.fetch(:start_date, Date.today).to_date
    # @meetings = Event.where(start_date: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  def show
    @team = current_user.team
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
    @team = Team.find(params[:team_id])
  end

  def create
    @event = Event.new(set_params)
    @team = current_user.team
    @event.team = @team
    @event.save
    if @event.save
      @event.player_ids = params[:event][:player_ids] || []
      @event.employee_ids = params[:event][:employee_ids] || []
      redirect_to team_event_path(@event.team_id, @event.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
    @team = current_user.team
    @event.team = @team
  end

  def update
    @event = Event.find(params[:id])
    @team = current_user.team
    @event.team = @team
    if @event.update(set_params)
      @event.player_ids = params[:event][:player_ids] || []
      @event.employee_ids = params[:event][:employee_ids] || []
      redirect_to team_event_path(@event.team_id, @event.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def health_status
    Player.all.map do |player|
      if player.health == "Available"
        "health-status available"
      elsif player.health == "Limited"
        "health-status limited"
      else
        "health-status injured"
      end
    end
  end

  private

  def set_params
    params.require(:event).permit(:title, :description, :location, :start_date, :end_date, :players, :event_type, :opposition)
  end
end

app/views/events/_event_card.html.erb
<div class="d-flex justify-content-center">
  <div class="mt-2 first-row-dashboard col-4 bg-white rounded-4 w-75">
      <div class="m-2 position-relative">
        <%= link_to edit_team_event_path(@team) do %>
          <i class="fa-solid fa-2x fa-pen-to-square position-absolute top-0 end-0 " style="color: #d7dde3;"></i>
        <% end %>

        <%= link_to team_events_path do %>
          <i class="fas fa-2x fa-chevron-circle-left" style="color: #dddddd;"></i>
        <% end %>

          <div class="row justify-content-center p-2">
            <h3 class="text-center p-2"><%= @event.title %></h3>
            <hr>
          </div>
          <div class="d-flex justify-content-center">
            <div class="d-flex w-75 pt-3">
                  <div class="col-8 ps-4 mb-2">
                    <h5>Description:</h5>
                    <h6 class="my-2 ms-2"><%= @event.description %></h6>
                    <h5>Location:</h5>
                    <h6 class="my-2 ms-2"><%= @event.location %></h6>
                    <h5>Who's participating</h5>
                      <h6 class="my-2 ms-2">Players:</h6>
                        <div class="div-height ms-3">
                          <% @event.players.to_a.each do |player| %>
                            <% if player.health === "Limited" %>
                              <div class="names limited mt-0">
                                <%= player.full_name %>
                              </div>
                            <% elsif player.health === "Injured" %>
                              <div class="names injured mt-0">
                                <%= player.first_name %>
                              </div>
                            <% else %>
                              <div class="names available mt-0 ">
                                <%= player.full_name %>
                              </div>
                            <% end %>
                          <% end %>
                        </div>
                        <h6 class="my-2 ms-2">Employees:</h6>
                          <div class="div-height ms-3">
                            <% @event.employees.to_a.each do |employee| %>
                              <div class="employees ms-0 mt-0">
                                <%= employee.first_name%>
                              </div>
                            <% end %>
                          </div>
                    </div>
                  <div class="col-4 pe-4 text-end mb-2">
                    <h5>Starts at:</h5>
                      <h6><%= @event.start_date.to_date.strftime("%-d %b %Y") %></h6>
                      <h6><%= @event.start_date.strftime("%H:%M") %>H</h6>
                    <h5>Ends at:</h5>
                      <h6><%= @event.start_date.to_date.strftime("%-d %b %Y") %></h6>
                      <h6><%= @event.end_date.strftime("%H:%M") %>H</h6>
                  </div>
            </div>
        </div>
      </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="all" data-controller="select-all">


  <%= simple_form_for [team, event] do |f|  %>
    <%= f.input :title,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Title" } %>
    <%= f.input :description,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Description" } %>
    <%= f.input :location,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Location" } %>
    <%= f.input :event_type,
                label: false,
                collection: Event::EVENT_TYPE,
                prompt: "Event Type",
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Event Type" }%>
    <%= f.input :opposition,
                label: false,
                collection: Event::OPPONENTS.keys,
                prompt: "Opposition",
                input_html: { autocomplete: "email", style: "background: white;" }%>
    <%= f.input :start_date,
                as: :string,
                input_html: { data: { controller: "datepicker" } } %>
    <%= f.input :end_date,
                as: :string,
                input_html: { data: { controller: "datepicker" } } %>
    <%= f.association :players,
                      collection: Player.where(health: "Available"),
                      as: :check_boxes,
                      label_method: :full_name,
                      value_method: :id,
                      input_html: { multiple: true },
                      input_html: { class: "tag-selector-available player" },
                      item_wrapper_class: 'tag-item' %>
    <%= f.association :players,
                      legend_tag: false,
                      collection: Player.where(health: "Limited"),
                      as: :check_boxes,
                      label_method: :full_name,
                      value_method: :id,
                      input_html: { multiple: true },
                      input_html: { class: "tag-selector-limited player" },
                      item_wrapper_class: 'tag-item' %>
    <%= f.association :players,
                      legend_tag: false,
                      collection: Player.where(health: "Injured"),
                      as: :check_boxes,
                      label_method: :full_name,
                      value_method: :id,
                      input_html: { multiple: true },
                      input_html: { class: "tag-selector-injured player" },
                      item_wrapper_class: 'tag-item' %>
    <div class="select-all" data-select-all-target="input" data-action="click->select-all#selection">
      Select All Players
    </div>
    <%= f.association :employees, as: :check_boxes, label_method: :employee_full_name, value_method: :id, input_html: { multiple: true }, input_html: { class: "tag-selector employee" }, item_wrapper_class: 'tag-item' %>
      <div class="select-all" data-select-all-target="employee" data-action="click->select-all#employee_selection">
        Select All Employees
      </div>
    <div>
    <%= f.button :submit, class: 'custom-button btn btn-primary' %>
    </div>
  <% end %>

</div>

app/views/events/edit.html.erb
<div class="container h-100 d-flex align-items-center justify-content-center">
  <div class="login form p-5 w-50 shadow mt-5 bg-white rounded-4">

    <%= link_to team_event_path(@team, @event) do %>
      <i class="fas fa-2x fa-chevron-circle-left" style="color: #dddddd;"></i>
    <% end %>

    <h2 class="text-center text-primary">Edit Event</h2>
    <div class="mt-3">
      <%= render 'form', team: @team, event: @event%>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<%# <% @events.each do |event| %>
  <%# <p><%= event.title</p> %>
  <%# <%= link_to 'See more', team_event_path(@team, event) %>
<%# <% end %>
<div class="d-flex flex-column align-items-center">
  <div class="w-100 d-flex justify-content-end me-2">
    <%= link_to new_team_event_path(@team) do %>
      <i class="fa-solid fa-circle-plus fa-4x m-2" style="color: #ffffff;"></i>
    <% end %>
  </div>

    <%= month_calendar(events: @events) do |date, events| %>
      <%= date.day %>
      <div class="event-div d-flex flex-column align-items-center justify-content-start card-header pt-1">
        <% events.each do |event| %>
          <div class="my-1 pb-4 px-2 title-div rounded-5">
            <p class="calendar-title"><%= link_to event.title, team_event_path(event.team_id, event.id) %></p>
          </div>
        <% end %>
      </div>
    <% end %>

</div>

app/views/events/new.html.erb
<div class="container h-100 d-flex align-items-center justify-content-center">
  <div class="login form p-5 w-50 shadow mt-5 bg-white rounded-4">

    <%= link_to team_events_path do %>
      <i class="fas fa-2x fa-chevron-circle-left" style="color: #dddddd;"></i>
    <% end %>

    <h2 class="text-center text-primary">Add Event</h2>
    <div class="mt-3">
      <%= render 'form', team: @team, event: @event %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<%# <%= @event.title %>
<%# <%= @event.location %>
<div class="row justify-content-center">
  <%= render 'event_card' %>
</div>