config/routes.rb
Rails.application.routes.draw do
  # mount Blazer::Engine, at: "blazer"
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "/teams/:id/staff", to: "teams#staff", as: "staff"
  get "/teams/:id/management", to: "management#index", as: "management"
  get "/teams/:id/chat", to: "teams#chat", as: "chat"
  get '/search', to: 'search#search'
  
  resources :teams, only: :show do
    resources :management, only: [:index, :show]

    resources :chatrooms do
      resources :messages, only: :create
    end

    resources :events, except: :destroy
    resources :players, except: :destroy
    resources :employees, except: :destroy
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :event_players, dependent: :destroy
  has_many :events, through: :event_players
  has_many :notifications, dependent: :destroy
  has_one_attached :photo

  HEALTH = %w[Injured Available Limited]

  validates :first_name, :last_name, :position, :birthdate, presence: true
  validates :health, inclusion: { in: HEALTH }
  validates :note, length: { maximum: 1000 }

  def full_name
    "#{first_name} #{last_name}"
  end

  include PgSearch::Model
  multisearchable against: %i[first_name last_name health]
  PgSearch.multisearch_options = {
    using: { tsearch: { prefix: true } }
  }
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_players, only: %i[show edit update]
  before_action :set_team

  def index
    @players = Player.all
    if params[:search].present?
      search_player
    end
  end

  def show
    @events = @player.events.order(start_date: :asc)
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    @player.team = @team
    @player.save
    if @player.save
      redirect_to team_players_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @player.update(player_params)
    if @player.saved_change_to_health?
      Notification.create!(team: @team, player: @player, note: "Health Update", column_name: "Player")
    elsif @player.saved_change_to_note?
      Notification.create!(team: @team, player: @player, note: "Player Update", column_name: "Player")
    elsif @player.saved_change_to_nutrition_restrictions?
      Notification.create!(team: @team, player: @player, note: "Nutrition Update", column_name: "Player")
    elsif @player.saved_change_to_expected_return_date?
      Notification.create!(team: @team, player: @player, note: "Return Update", column_name: "Player" )
    end
    redirect_to team_player_path(@player)
    @player.save

  end

  private

  def search_player
    PgSearch::Multisearch.rebuild(Player)
    results = PgSearch.multisearch(params[:search])
    @players = results.map { |player| player.searchable}
  end

  def set_players
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(
      :first_name,
      :last_name,
      :birthdate,
      :position,
      :health,
      :availability,
      :photo,
      :note,
      :nutrition_restrictions,
      :injury_notes,
      :preferred_side,
      :expected_return_date
    )
  end

  def set_team
    @team = current_user.team
    # @team = Team.find(params[:team_id])
  end
end

app/views/players/_form.html.erb
<%= simple_form_for [team, player] do |f| %>
    <%= f.input :first_name,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "First name" }%>
    <%= f.input :last_name,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Last name" }%>
    <%= f.input :position,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Position" }%>
    <%= f.input :birthdate,
                as: :string,
                input_html: { data: { controller: "datepicker" } },
                label_html: { class: "h6", style: "color: #2D7D9F;"} %>
    <%= f.input :health,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Health" }%>
    <%= f.input :injury_notes,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Injury Notes" }%>
    <%= f.input :nutrition_restrictions,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Nutrition Restrictions" }%>
    <%= f.input :preferred_side,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Preferred Side" }%>
    <%= f.input :note,
                label: false,
                input_html: { autocomplete: "email", style: "background: white;", placeholder: "Notes" }%>
    <%= f.input :expected_return_date,
                as: :string,
                input_html: { data: { controller: "datepicker" } },
                label_html: { class: "h6", style: "color: #2D7D9F;"} %>

    <%= f.submit class: 'custom-button btn btn-primary'%>
<% end %>

app/views/players/_player_card.html.erb
<div class="col-12 col-md-4">
  <%= link_to team_player_path(@team, player) do %>
    <div class="player-card d-flex rounded-4">
      <%= cl_image_tag player.photo.key, width: 100 %>
      <div class="staff-text">
        <h5><%= player.first_name %> <%= player.last_name %></h5>
        <h6><%= player.position %></h6>
        <% if player.health == "Available" %>
          <div class="health-status available mt-3 mb-1">
            <%= player.health%>
          </div>
        <% elsif player.health == "Limited" %>
          <div class="health-status limited mt-3 mb-1" >
            <%= player.health%>
          </div>
        <% else %>
          <div class="health-status injured mt-3 mb-1">
            <%= player.health%>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/players/edit.html.erb
<div class="container h-100 d-flex align-items-center justify-content-center">
  <div class="login form p-5 w-50 shadow mt-5 bg-white rounded-4">

    <%= link_to team_players_path do %>
      <i class="fas fa-2x fa-chevron-circle-left" style="color: #dddddd;"></i>
    <% end %>

    <h2 class="text-center text-primary">Edit Player</h2>
    <div class="mt-3">
      <%= render "form", player: @player, team: @team %>
    </div>
  </div>
</div>

app/views/players/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <div class="d-flex">
      <div class="players-title d-flex align-items-center">
        <h3>Players</h3>
      </div>
      <%= link_to new_team_player_path(@team) do %>
        <i class="fa-solid fa-circle-plus fa-3x m-3" style="color: #ffffff;"></i>
      <% end %>
    </div>
    <div class="navigation-links d-flex align-items-end me-3">
      <%= link_to "Back to team dashboard", team_path(@team) %>
    </div>
  </div>
  <div class="d-flex row">
    <% @players.each do |player| %>
      <%= render "player_card", player: player %>
    <% end %>
  </div>
</div>

app/views/players/new.html.erb
<div class="container h-100 d-flex align-items-center justify-content-center">
  <div class="login form p-5 w-50 shadow mt-5 bg-white rounded-4">

    <%= link_to team_players_path(@team) do %>
      <i class="fas fa-2x fa-chevron-circle-left" style="color: #dddddd;"></i>
    <% end %>
    <h2 class="text-center text-primary">Add Player</h2>

    <div class="mt-3">
      <%= render "form", player: @player, team: @team %>
    </div>

  </div>
</div>

app/views/players/show.html.erb
<div class="ms-5 d-flex justify-content-center">
  <div class="player-profile-div col-7 bg-white rounded-4 m-5">
    <div class="row pt-2 ps-2 pe-2">
      <div class="col-6">
        <%= link_to staff_path do %>
          <i class="fas fa-2x fa-chevron-circle-left" style="color: #dddddd;"></i>
        <% end %>
      </div>
      <div class="col-6 d-flex justify-content-end">
        <%= link_to edit_team_player_path(@team, @player) do %>
          <i class="fa-solid fa-2x fa-pen-to-square" style="color: #dddddd;"></i>
        <% end %>
      </div>
    </div>

    <div class="row pt-1 px-3">
      <div class="col-6">
        <h2 class="fw-light ps-4 pb-1"><%= @player.first_name %> <%= @player.last_name %></h2>
        <h6 class="ps-4 pb-1"><%= @player.position %></h6>
      </div>

      <div class="col-6 justify-content-start pt-1">
        <% if @player.health == "Available" %>
          <div class="health-status available mt-2 ms-2">
            <%= @player.health %>
          </div>
        <% elsif @player.health == "Limited" %>
          <div class="health-status limited mt-2 ms-2" >
            <%= @player.health %>
          </div>
        <% else %>
          <div class="health-status injured mt-2 ms-2">
            <%= @player.health %>
          </div>
        <% end %>
      </div>
    </div>


    <div class="ps-4 pe-4">
      <hr>

      <%# player info %>
      <div class="row px-3">
        <div class="col-6">
          <h4 class="mb-3">Information</h4>
          <div class="d-flex">
            <i class="fa-solid fa-cake-candles me-3" style="color: #d9d9d9; font-size: 1.8em;"></i>
            <p><%= @player.birthdate.strftime("%d %B %Y") %></p>
          </div>

          <div class="d-flex">
            <i class="fa-solid fa-futbol me-3"  style="color: #d9d9d9; font-size: 1.8em;"></i>
            <p><%= @player.preferred_side %></p>
          </div>

          <% if @player.note.present? %>
            <div class="d-flex">
              <i class="fa-solid fa-note-sticky me-3" style="color: #d9d9d9; font-size: 1.8em;"></i>
              <p><%= @player.note %></p>
            </div>
          <% end %>
        </div>

        <div class="col-6">
          <h4 class="mb-3">Health Information</h4>

          <div class="d-flex">
            <i class="sidebar-button  fa-solid fa-utensils me-3" style="color: #d9d9d9; font-size: 1.8em;"></i>
            <p><%= @player.nutrition_restrictions %></p>
          </div>

          <% if @player.injury_notes.present? %>
            <div class="d-flex">
              <i class="sidebar-button fa-solid fa-notes-medical me-3" style="color: #d9d9d9; font-size: 1.8em;"></i>
              <p><%= @player.injury_notes %></p>
            </div>
          <% end %>

          <% if @player.expected_return_date.present? %>
            <div class="d-flex">
              <i class="fa-solid fa-person-walking-arrow-loop-left me-3" style="color: #d9d9d9; font-size: 1.8em;"></i>
              <p><%= @player.expected_return_date.strftime("%d %B %Y") %></p>
            </div>
          <% end %>

        </div>
      </div>

      <hr>
      <%# player events%>
      <div class="row flex-column px-3">
        <h4 class="mb-3">Todays Events</h4>
        <% @events.each do |event| %>
          <% if event.start_date.to_date == Date.today() %>
            <div class="col-6 mb-2 pt-1 px-3">
              <div class="d-flex">
                <div class="d-flex align-items-center me-2">
                  <h6><%= event.start_date.strftime("%H:%M")%></h6>
                </div>
                <h6><%= event.title %></h6>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-5 d-flex justify-content-start ps-5 align-items-center" style="height: 600px;">
    <%# player photo %>
    <%= cl_image_tag @player.photo.key, class: "img-fluid player-image" %>
  </div>
</div>